### ISSUE TITLE
Exception in plugin (0.1.2)

### ISSUE THREAD

**Issue by mrEckendonk** [lppedd/idea-conventional-commit-commitlint#7]
### When this plugin is enabled, an IDE Internal Error pops up

```
java.lang.InstantiationError: com.github.lppedd.cc.api.ProviderPresentation
	at com.github.lppedd.cc.commitlint.CommitlintConstants.<clinit>(CommitlintConstants.kt:9)
	at com.github.lppedd.cc.commitlint.CommitlintTokensProvider.getPresentation(CommitlintTokensProvider.kt:24)
	at com.github.lppedd.cc.completion.menu.FilterAction.<init>(FilterAction.kt:22)
	at com.github.lppedd.cc.completion.LookupEnhancer.setProviders(LookupEnhancer.kt:72)
	at com.github.lppedd.cc.completion.ConventionalCommitTextCompletionContributor.enhanceCompletionProcessIndicator(ConventionalCommitTextCompletionContributor.kt:254)
	at com.github.lppedd.cc.completion.ConventionalCommitTextCompletionContributor.fillCompletionVariants(ConventionalCommitTextCompletionContributor.kt:205)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$getVariantsFromContributor$1(CompletionServiceImpl.java:321)
	at com.intellij.diagnostic.telemetry.TraceKt.runWithSpan(trace.kt:74)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.java:320)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:56)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:40)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.lambda$performCompletion$2(CompletionServiceImpl.java:338)
	at com.intellij.diagnostic.telemetry.TraceKt.runWithSpan(trace.kt:74)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:327)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$11(CompletionProgressIndicator.java:870)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:202)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:723)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:201)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:866)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:854)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:371)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:167)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$8(CodeCompletionHandlerBase.java:363)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
### Installed plugins that might cause a conflict: 
.env files support (2022.3)
.ignore (4.4.4)
Atom Material Icons (85.1.0)
Cobalt 2 (1.0)
CodeGlance Pro (1.5.9)
CommitLint (0.0.4)
Commitlint Conventional Commit (0.1.2)
Conventional Commit (0.21.0)
CSV Editor (3.0.2-223)
CVS (223.0)
Database Tools and SQL for WebStorm (223.8214.51)
Extra Icons (2022.1.14)
git bisect run (0.7.6)
Git Commit Template (1.2.0)
GitHub Copilot (1.1.38.2229)
GitToolBox (213.10.5)
GraphQL (3.3.0)
HTML Entity (1.1)
IDEA Mind Map (1.6.0.2)
Key Promoter X (2022.3)
MDX (223.8214.16)
PostCSS (223.7571.117)
PostgreSQL Debugger (222.3.0)
PowerShell (2.0.10)
Rainbow Brackets (2023.1.1)
Randomness (2.7.6)
Smart Search (2023.1.1)
SonarLint (7.3.0.59206)
String Manipulation (9.6.1)
Tailwind CSS Smart Completions (1.4.0)
Tailwind Formatter (1.5.1)
Translation (3.4.1)
WakaTime (14.1.3)
Docker (223.8214.51)
FTP/SFTP/WebDAV Connectivity (223.8214.51)
Vagrant (223.8214.51)
HTML Tools (223.8214.51)
Live Edit (223.8214.51)
Refactor-X (223.8214.51)
Settings Sync (223.8214.51)
Angular and AngularJS (223.8214.51)
Cucumber.js (223.8214.51)
JavaScript Debugger (223.8214.51)
JavaScript Intention Power Pack (223.8214.51)
Karma (223.8214.51)
Next.js Support (223.8214.51)
Node.js (223.8214.51)
Node.js Remote Interpreter (223.8214.51)
Polymer & Web Components (223.8214.51)
Prettier (223.8214.51)
TSLint (223.8214.51)
Vite (223.8214.51)
Vue.js (223.8214.51)
Webpack (223.8214.51)
Eclipse Keymap (223.8214.51)
NetBeans Keymap (223.8214.51)
Visual Studio Keymap (223.8214.51)
VSCode Keymap (223.8214.51)
Gherkin (223.8214.51)
Markdown (223.8214.51)
Shell Script (223.8214.51)
YAML (223.8214.51)
Remote Development Gateway (223.8214.51)
CSS (223.8214.51)
Less (223.8214.51)
Sass (223.8214.51)
Tailwind CSS (223.8214.51)
EJS (223.8214.51)
Handlebars/Mustache (223.8214.51)
Pug (ex-Jade) (223.8214.51)
All Hallow's Eve Color Scheme (223.8214.51)
Blackboard Color Scheme (223.8214.51)
Cobalt Color Scheme (223.8214.51)
Github Color Scheme (223.8214.51)
Monokai Color Scheme (223.8214.51)
Railscasts Color Scheme (223.8214.51)
Twilight Color Scheme (223.8214.51)
VibrantInk Color Scheme (223.8214.51)
WarmNeon Color Scheme (223.8214.51)
Git (223.8214.51)
GitHub (223.8214.51)
Mercurial (223.8214.51)
Subversion (223.8214.51)
Code With Me (223.8214.51)
Copyright (223.8214.51)
Diagrams (223.8214.51)
EditorConfig (223.8214.51)
File Watchers (223.8214.51)
Grazie (223.8214.51)
HTTP Client (223.8214.51)
IntelliLang (223.8214.51)
Machine Learning Code Completion (223.8214.51)
Machine Learning in Search Everywhere (223.8214.51)
Package Checker (223.8214.51)
Performance Testing (223.8214.51)
Qodana (223.8214.51)
Shared Project Indexes (223.8214.51)
Space (223.8214.51)
Styled Components & Styled JSX (223.8214.51)
Task Management (223.8214.51)
Terminal (223.8214.51)
TextMate Bundles (223.8214.51)
Time Tracking (223.8214.51)
WebP Support (223.8214.51)

**Comment by psoares** [comment]
I got the same error today.

**Comment by franckrasolo** [comment]
Try the [workaround](https://github.com/lppedd/idea-conventional-commit-commitlint/issues/11#issuecomment-1483898349) suggested by @lppedd in #11.
